In [ ]:
import pandas as pd
from sklearn.datasets import load_wine

In [ ]:
wine=load_wine()

In [ ]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [ ]:
df=pd.DataFrame(wine.data,columns=wine.feature_names)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [ ]:
df['target']=wine.target
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [ ]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [ ]:
x=df.drop('target',axis='columns')
y=df.target

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_test)

GaussianNB()

In [ ]:
gnb.score(x_test,y_train)

1.0

In [ ]:
gnb.predict(x_test[:10])

array([2, 1, 0, 1, 0, 2, 1, 0, 2, 1])

In [ ]:
y_test[:10]

91     1
81     1
114    1
48     0
54     0
59     1
165    2
39     0
56     0
44     0
Name: target, dtype: int64

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(x_train,y_test)

MultinomialNB()

In [ ]:
mnb.score(x_test,y_train)

0.8333333333333334

In [ ]:
mnb.predict(x_test[:10])

array([2, 1, 0, 1, 0, 2, 1, 0, 2, 1])

In [ ]:
y_test[:10]

91     1
81     1
114    1
48     0
54     0
59     1
165    2
39     0
56     0
44     0
Name: target, dtype: int64

In [ ]:
gaussian_score=gnb.score(x_test,y_train)
multinomial_score=mnb.score(x_test,y_train)
print("gaussian_score:",gaussian_score)
print("multinomial_score:",multinomial_score)

gaussian_score: 1.0
multinomial_score: 0.8333333333333334

In [ ]:
if gaussian_score>multinomial_score:
    print("gaussian_score is better")
else:
    print("multinomial_score is better")

gaussian_score is better

In [28]:
import joblib

In [29]:
joblib.dump(gnb,"naive_bayes_wine.joblib")

['naive_bayes_wine.joblib']