<a href="https://colab.research.google.com/github/moniml/mlopstraining/blob/main/Multi_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,
2 yr experience, 9 test score, 6 interview score
12 yr experience, 10 test score, 10 interview score

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [ ]:
df = pd.read_csv("/content/hiring.csv")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
df.experience=df.experience.fillna("zero")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
df.experience=df.experience.apply(w2n.word_to_num)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [ ]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [ ]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [ ]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

In [ ]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([93747.79628651])

Own dataset

SOCIAL MEDIA ADDICTION PREDICTION

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
df = pd.read_csv("/content/social_media_addiction_dataset (1).csv")

In [ ]:
print(df.head())
print(df.info())
print(df.isnull().sum())

   daily_screen_time  app_opens  sleep_hours  stress_level  \
0                5.4         67          3.8             1
1                4.3         10          6.9             2
2                7.0         48          5.4             9
3               12.0         16          6.7             2
4                8.8         25          6.0             3

   study_interruptions night_usage addiction_level
0                    2          No        Moderate
1                    7          No             Low
2                    3          No        Moderate
3                    0          No             Low
4                   15          No        Moderate
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   daily_screen_time    1000 non-null   float64
 1   app_opens            1000 non-null   int64
 2   sleep_hours          1000 non-null   float64
 3   stress_level         1000 non-null   int64
 4   study_interruptions  1000 non-null   int64
 5   night_usage          1000 non-null   object
 6   addiction_level      1000 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 54.8+ KB
None
daily_screen_time      0
app_opens              0
sleep_hours            0
stress_level           0
study_interruptions    0
night_usage            0
addiction_level        0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df = df.fillna(df.mean(numeric_only=True))

In [ ]:
if 'night_usage' in df.columns:
    df = pd.get_dummies(df, columns=['night_usage'], drop_first=True)

# Map addiction_level to numerical values
addiction_mapping = {'Low': 0, 'Moderate': 1, 'High': 2}
df['addiction_level'] = df['addiction_level'].map(addiction_mapping)

X = df[['daily_screen_time',
        'app_opens',
        'sleep_hours',
        'stress_level',
        'study_interruptions',
        'night_usage_Yes']]

y = df['addiction_level']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 0.2602108724192593
MSE: 0.09869709127967848
RMSE: 0.3141609321345964
R2 Score: 0.6110842625172752

In [ ]:
coeff_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print(coeff_df)
print("Intercept:", model.intercept_)

               Feature  Coefficient
0    daily_screen_time     0.060463
1            app_opens     0.009285
2          sleep_hours    -0.116149
3         stress_level     0.074095
4  study_interruptions     0.036313
5      night_usage_Yes     0.250524
Intercept: 0.17846724517967294