<a href="https://colab.research.google.com/github/moniml/mlopstraining/blob/main/one_hot_own.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv("/content/social_media_addiction_dataset (1).csv")
df

,daily_screen_time,app_opens,sleep_hours,stress_level,study_interruptions,night_usage,addiction_level
0,5.4,67,3.8,1,2,No,Moderate
1,4.3,10,6.9,2,7,No,Low
2,7.0,48,5.4,9,3,No,Moderate
3,12.0,16,6.7,2,0,No,Low
4,8.8,25,6.0,3,15,No,Moderate
...,...,...,...,...,...,...,...
995,2.8,49,6.6,7,9,No,Moderate
996,6.5,76,5.4,7,3,No,Moderate
997,6.5,22,6.6,1,5,Yes,Moderate
998,4.0,40,4.3,8,13,No,Moderate
999,5.0,27,6.2,10,12,No,Moderate

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   daily_screen_time    1000 non-null   float64
 1   app_opens            1000 non-null   int64
 2   sleep_hours          1000 non-null   float64
 3   stress_level         1000 non-null   int64
 4   study_interruptions  1000 non-null   int64
 5   night_usage          1000 non-null   object
 6   addiction_level      1000 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 54.8+ KB

In [9]:
dummies = pd.get_dummies(df.night_usage, dtype=int)
dummies

     No  Yes
0     1    0
1     1    0
2     1    0
3     1    0
4     1    0
..   ..  ...
995   1    0
996   1    0
997   0    1
998   1    0
999   1    0

[1000 rows x 2 columns]

In [10]:
merged=pd.concat([df,dummies],axis='columns')
merged

,daily_screen_time,app_opens,sleep_hours,stress_level,study_interruptions,night_usage,addiction_level,No,Yes
0,5.4,67,3.8,1,2,No,Moderate,1,0
1,4.3,10,6.9,2,7,No,Low,1,0
2,7.0,48,5.4,9,3,No,Moderate,1,0
3,12.0,16,6.7,2,0,No,Low,1,0
4,8.8,25,6.0,3,15,No,Moderate,1,0
...,...,...,...,...,...,...,...,...,...
995,2.8,49,6.6,7,9,No,Moderate,1,0
996,6.5,76,5.4,7,3,No,Moderate,1,0
997,6.5,22,6.6,1,5,Yes,Moderate,0,1
998,4.0,40,4.3,8,13,No,Moderate,1,0
999,5.0,27,6.2,10,12,No,Moderate,1,0

In [12]:
final=merged.drop(['night_usage'],axis='columns')
final

,daily_screen_time,app_opens,sleep_hours,stress_level,study_interruptions,addiction_level,No,Yes
0,5.4,67,3.8,1,2,Moderate,1,0
1,4.3,10,6.9,2,7,Low,1,0
2,7.0,48,5.4,9,3,Moderate,1,0
3,12.0,16,6.7,2,0,Low,1,0
4,8.8,25,6.0,3,15,Moderate,1,0
...,...,...,...,...,...,...,...,...
995,2.8,49,6.6,7,9,Moderate,1,0
996,6.5,76,5.4,7,3,Moderate,1,0
997,6.5,22,6.6,1,5,Moderate,0,1
998,4.0,40,4.3,8,13,Moderate,1,0
999,5.0,27,6.2,10,12,Moderate,1,0

In [23]:
x=final.drop('addiction_level',axis='columns')
y=final['addiction_level']
y

0      Moderate
1           Low
2      Moderate
3           Low
4      Moderate
         ...
995    Moderate
996    Moderate
997    Moderate
998    Moderate
999    Moderate
Name: addiction_level, Length: 1000, dtype: object

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [21]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [22]:
model.score(x_test,y_test)

0.88

In [17]:
model.predict(x_test)

array(['High', 'High', 'Moderate', 'Moderate', 'Low', 'Moderate',
       'Moderate', 'Moderate', 'Moderate', 'Moderate', 'Moderate', 'High',
       'Moderate', 'Moderate', 'Moderate', 'High', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'Low', 'Moderate', 'Moderate', 'High',
       'Moderate', 'Low', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'High', 'High', 'Moderate', 'Moderate', 'Moderate',
       'High', 'Moderate', 'Low', 'Moderate', 'Moderate', 'High',
       'Moderate', 'Moderate', 'Moderate', 'Low', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'High', 'Moderate', 'Moderate', 'High',
       'Moderate', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'Low', 'Moderate', 'Low', 'Moderate', 'High', 'Low',
       'Moderate', 'Low', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'High', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'Low', 'Moderate', 'High', 'Moderate',
       'Moderate', 'Moderate', 'Low', 'High', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'High', 'Moderate', 'High', 'Moderate',
       'Moderate', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'Moderate', 'Moderate', 'High', 'Moderate',
       'Moderate', 'High', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'High', 'Moderate', 'Moderate', 'Moderate', 'Low',
       'High', 'High', 'High', 'Moderate', 'Moderate', 'Low', 'Moderate',
       'Low', 'Moderate', 'Moderate', 'Moderate', 'Moderate', 'High',
       'Moderate', 'Moderate', 'High', 'Moderate', 'Moderate', 'High',
       'Moderate', 'Low', 'Moderate', 'Low', 'Low', 'Moderate',
       'Moderate', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'Moderate', 'Moderate', 'High', 'Moderate', 'Low',
       'Moderate', 'Low', 'Moderate', 'Moderate', 'Moderate', 'Low',
       'High', 'High', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Moderate', 'High', 'Moderate', 'Moderate', 'Moderate', 'Moderate',
       'Low', 'Moderate', 'Low', 'High', 'Moderate', 'High', 'Moderate',
       'Moderate', 'High', 'Moderate', 'Moderate', 'High', 'High',
       'Moderate', 'Moderate', 'Moderate', 'Moderate'], dtype=object)

Predict addiction level of a student with:
8 hours daily screen time
65 app opens
5 hours sleep
stress level 8
6 study interruptions
night usage = Yes

In [25]:
new=pd.DataFrame([[8,65,5,8,6,0,1]],columns=['daily_screen_time','app_opens','sleep_hours','stress_level','study_interruptions','No','Yes'])
prediction=model.predict(new)
print(prediction)

['High']

Predict addiction risk for a user who:
spends 3 hours daily on social media
opens apps 15 times
sleeps 8 hours
stress level 2
study interruptions 1
night usage = No

In [26]:
new=pd.DataFrame([[3,15,8,2,1,1,0]],columns=['daily_screen_time','app_opens','sleep_hours','stress_level','study_interruptions','No','Yes'])
prediction=model.predict(new)
print(prediction)

['Low']